artifacts_root: artifacts


data_ingestion : 
  root_dir: artifacts/data_ingestion
  source_URL : "https://github.com/kv1729/datasets/raw/main/Chiken-fecal-images.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion